using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Futbol5.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class FixUsersIdAutoIncrement : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // La tabla Users fue creada con la migración InitialPostgresSchema usando
            // tipos de SQLite (INTEGER con Sqlite:Autoincrement). PostgreSQL ignora
            // esa anotación, así que la columna Id queda sin secuencia/identidad.
            // Al intentar INSERT sin valor explícito, se inserta 0 y el segundo
            // INSERT falla por clave duplicada, o directamente da error.
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                // 1. Cambiar el tipo de INTEGER (alias de int4 en PG) a int (por claridad)
                //    y agregar GENERATED BY DEFAULT AS IDENTITY para autoincremento.
                migrationBuilder.Sql(
                    @"CREATE SEQUENCE IF NOT EXISTS ""Users_Id_seq"" OWNED BY ""Users"".""Id"";
                      SELECT setval('""Users_Id_seq""', COALESCE(MAX(""Id""), 0) + 1, false) FROM ""Users"";
                      ALTER TABLE ""Users"" ALTER COLUMN ""Id"" SET DEFAULT nextval('""Users_Id_seq""');"
                );
            }
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql(
                    @"ALTER TABLE ""Users"" ALTER COLUMN ""Id"" DROP DEFAULT;
                      DROP SEQUENCE IF EXISTS ""Users_Id_seq"";"
                );
            }
        }
    }
}

